name: docker

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0 # Checkout the whole branch

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push server
        uses: docker/build-push-action@v4
        with:
          push: true
          file: docker/server.Dockerfile
          tags: tiechui1994/tcpover:latest
      - name: Build and push agent
        uses: docker/build-push-action@v4
        with:
          push: true
          file: docker/ubuntu.Dockerfile
          tags: tiechui1994/tcpover-agent:latest